openapi: 3.0.0
info:
  title: API Example
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: "Autenticación de usuario"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Token generado exitosamente"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: "Credenciales inválidas"

  /hello/common:
    get:
      summary: "Endpoint accesible por cualquier usuario autenticado"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Mensaje de saludo común"

  /hello/user1:
    get:
      summary: "Endpoint exclusivo para User1"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Mensaje de saludo para User1"
        "403":
          description: "Acceso denegado"

  /hello/user2:
    get:
      summary: "Endpoint exclusivo para User2"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Mensaje de saludo para User2"
        "403":
          description: "Acceso denegado"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
